export default {
  SET_JOKES: 'JOKES.SET_JOKES',
  SET_STARRED_JOKES: 'JOKES.SET_STARRED_JOKES',
  SET_STARRED_JOKE_IDS: 'JOKES.SET_STARRED_JOKE_IDS',
  TOGGLE_STARRED_JOKE: 'JOKES.TOGGLE_STARRED_JOKE',
};
